[package]
name = "loco-rs"
version = "0.1.0"
edition = "2021"
description = "The 1-Person Framework for rust"
license = "Apache-2.0"
homepage = "https://docs.rs/loco-rs"
documentation = "https://docs.rs/loco-rs"
authors = ["Dotan Nahum <dotan@rng0.io>", "Elad Kaplan <kaplan.elad@gmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["auth", "cli", "with-db"]

auth = ["dep:jsonwebtoken", "dep:bcrypt"]
cli = ["dep:clap"]
testing = ["dep:axum-test"]
with-db = ["dep:sea-orm", "dep:sea-orm-migration"]

[dependencies]

eyre = "0.6"

# cli
clap = { version = "4.4.7", features = ["derive"], optional = true }
colored = "2"


sea-orm = { version = "0.12.4", features = [
  "sqlx-postgres",        # `DATABASE_DRIVER` feature
  "sqlx-sqlite",
  "runtime-tokio-rustls",
  "macros",
], optional = true }

tokio = { version = "1.33.0", features = ["full"] }
# the rest

serde = "1"
serde_json = "1"
serde_yaml = "0.9"
serde_variant = "0.1.2"

# worker fwk 
rusty-sidekiq = { version = "0.8.2", default-features = false }
async-trait = "0.1.74"
bb8 = "0.8.1"

axum = "0.7.1"
regex = "1"
lazy_static = "1.4.0"
fs-err = "2.11.0"
# mailer
tera = "1.19.1"
lettre = { version = "0.11.1", default-features = false, features = [
  "builder",
  "hostname",
  "smtp-transport",
  "tokio1-rustls-tls",
] }
include_dir = "0.7.3"
thiserror = "1"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }


# cli/migrations
duct = "0.13.6"

config = "0.13.3"
tower-http = { version = "0.5.0", features = ["trace", "catch-panic"] }
byte-unit = "4.0.19"

jsonwebtoken = { version = "9.1.0", optional = true }
bcrypt = { version = "0.15.0", optional = true }
validator = { version = "0.16.1", features = ["derive"] }

axum-test = { version = "14.0.0-rc.1", optional = true }

# gen 
rrgen = "0.5.2"
chrono = "0.4.31"
cargo_metadata = "0.18.1"

cfg-if = "1"

uuid = { version = "1.6", features = ["v4"] }


[dependencies.sea-orm-migration]
optional = true
version = "0.12.4"
features = [
  # Enable at least one `ASYNC_RUNTIME` and `DATABASE_DRIVER` feature if you want to run migration via CLI.
  # View the list of supported features at https://www.sea-ql.org/SeaORM/docs/install-and-config/database-and-async-runtime.
  # e.g.
  "runtime-tokio-rustls", # `ASYNC_RUNTIME` feature
  "sqlx-postgres",        # `DATABASE_DRIVER` feature
  "sqlx-sqlite",
]


[dev-dependencies]
rstest = "0.18.2"
insta = { version = "1.34.0", features = ["redactions", "yaml", "filters"] }
